"""LangGraph Care Navigation & Doctor Visit Summary Workflow (Human-in-the-Loop)."""

from typing import Dict, Any
from langgraph.graph import StateGraph, END
from app.graphs.state import CareNavState


async def node_determine_specialty(state: CareNavState) -> Dict[str, Any]:
    specialty = "Cardiology / Internal Medicine"
    return {"recommended_specialty": specialty}


async def node_format_visit_summary(state: CareNavState) -> Dict[str, Any]:
    summary = (
        "PATIENT HEALTH VISIT SUMMARY (Generated by Personal Health OS)\n"
        f"Primary Reason: Resting metric deviation outside 30-day baseline.\n"
        f"Recommended Specialty: {state.get('recommended_specialty', 'Internal Medicine')}\n"
        "Disclaimer: This summary is generated from personal wearable telemetry for patient clinical consultation."
    )
    return {"visit_summary_text": summary}


def build_care_nav_graph() -> StateGraph:
    workflow = StateGraph(CareNavState)

    workflow.add_node("determine_specialty", node_determine_specialty)
    workflow.add_node("format_visit_summary", node_format_visit_summary)

    workflow.set_entry_point("determine_specialty")
    workflow.add_edge("determine_specialty", "format_visit_summary")
    workflow.add_edge("format_visit_summary", END)

    return workflow.compile()
