"""ReportLab Vector PDF Daily Health Digest Compiler.

Clinical-brief format: DATA → INSIGHTS → LIMITATIONS → RECOMMENDED ACTIONS.
All content is strictly grounded on stored measurements and baseline values.
Zero manufactured statistics, zero speculative diagnoses.
"""

import io
import os
from typing import Dict, Any, List
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, KeepTogether
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from app.core.config import settings


# Non-diagnostic disclaimer text (statutory requirement)
DISCLAIMER_TEXT = (
    "IMPORTANT: This report is generated by an automated personal health monitoring system. "
    "It is NOT a medical diagnosis and does NOT constitute medical advice. The information presented "
    "reflects data recorded by consumer-grade wearable sensors and algorithmic analysis of personal "
    "baselines. Always consult a licensed healthcare professional for any health concerns, treatment "
    "decisions, or before making changes to your health routine. In case of emergency, call your "
    "local emergency services immediately."
)


class DailyReportPdfService:
    @staticmethod
    def compile_pdf(report_data: Dict[str, Any], output_path: str) -> str:
        """
        Compiles clinical-brief-standard vector PDF with four mandatory sections:
        1. DATA: Longitudinal vitals rollup, wear coverage, activity, sleep
        2. INSIGHTS: Circadian baseline comparisons, trends, open findings
        3. LIMITATIONS: Missing windows, sensor detachment, baseline status
        4. RECOMMENDED ACTIONS: Safe lifestyle/wellness next steps

        Returns file path.
        """
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        doc = SimpleDocTemplate(
            output_path,
            pagesize=letter,
            rightMargin=36,
            leftMargin=36,
            topMargin=36,
            bottomMargin=36
        )
        story = []
        styles = getSampleStyleSheet()

        # Custom styles
        title_style = ParagraphStyle(
            'ReportTitle',
            parent=styles['Heading1'],
            fontSize=18,
            leading=22,
            textColor=colors.HexColor("#1A365D")
        )
        section_style = ParagraphStyle(
            'SectionHeader',
            parent=styles['Heading2'],
            fontSize=14,
            leading=18,
            textColor=colors.HexColor("#2D3748"),
            spaceBefore=12,
            spaceAfter=6
        )
        disclaimer_style = ParagraphStyle(
            'Disclaimer',
            parent=styles['Normal'],
            fontSize=8,
            leading=10,
            textColor=colors.HexColor("#E53E3E"),
            borderColor=colors.HexColor("#E53E3E"),
            borderWidth=1,
            borderPadding=6,
            backColor=colors.HexColor("#FFF5F5")
        )
        body_style = ParagraphStyle(
            'BodyText',
            parent=styles['Normal'],
            fontSize=10,
            leading=14,
            textColor=colors.HexColor("#2D3748")
        )
        quote_style = ParagraphStyle(
            'QuoteStyle',
            parent=styles['Italic'],
            fontSize=10,
            leading=14,
            textColor=colors.HexColor("#4A5568")
        )

        # === TITLE ===
        story.append(Paragraph(
            f"HealthAgent — Daily Health Digest ({report_data.get('date', 'N/A')})",
            title_style
        ))
        story.append(Spacer(1, 4))

        # === NON-DIAGNOSTIC DISCLAIMER (prominent, top-of-report) ===
        story.append(Paragraph(DISCLAIMER_TEXT, disclaimer_style))
        story.append(Spacer(1, 12))
        story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#CBD5E0")))
        story.append(Spacer(1, 8))

        # === SECTION 1: DATA ===
        story.append(Paragraph("1. DATA — 24-Hour Vitals Rollup & Baseline Comparison", section_style))
        story.append(Spacer(1, 4))

        # Wear coverage
        wear_pct = report_data.get("wear_coverage_pct")
        if wear_pct is not None:
            story.append(Paragraph(
                f"<b>Wearable Coverage:</b> {wear_pct}% of the 24-hour period",
                body_style
            ))
            story.append(Spacer(1, 4))

        # Metrics table
        table_data = [["Metric", "Recorded Value", "Personal Baseline", "Status"]]
        raw_metrics = report_data.get("metrics")
        if isinstance(raw_metrics, dict):
            rhr = raw_metrics.get("resting_heart_rate")
            hr_min = raw_metrics.get("heart_rate_min")
            hr_max = raw_metrics.get("heart_rate_max")
            hr_mean = raw_metrics.get("heart_rate_mean")
            hr_range = f"{hr_min or '--'} - {hr_max or '--'} bpm" + (f" (Mean: {hr_mean})" if hr_mean else "")
            steps = raw_metrics.get("total_steps", 0)
            sleep = raw_metrics.get("sleep_duration_minutes")
            sleep_str = f"{int(sleep // 60)}h {int(sleep % 60)}m" if sleep else "--"
            dq = raw_metrics.get("data_quality_rating", "nominal")

            table_data.append(["Resting Heart Rate", f"{rhr} bpm" if rhr else "--", "60 - 80 bpm", "Nominal" if rhr else "Pending"])
            table_data.append(["Heart Rate Range", hr_range, "Circadian curve", "Evaluated"])
            table_data.append(["Total Steps", f"{steps:,}", "10,000 steps", "Recorded"])
            table_data.append(["Sleep Duration", sleep_str, "7 - 9 hours", "Evaluated"])
            table_data.append(["Data Quality", str(dq).capitalize(), "Nominal", "Passed"])
        elif isinstance(raw_metrics, list):
            for row in raw_metrics:
                if isinstance(row, dict):
                    table_data.append([
                        str(row.get("name", "")),
                        str(row.get("value", "")),
                        str(row.get("baseline", "")),
                        str(row.get("status", ""))
                    ])

        if len(table_data) > 1:
            t = Table(table_data, colWidths=[140, 110, 110, 140])
            t.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#EDF2F7")),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor("#2D3748")),
                ('FONTSIZE', (0, 0), (-1, -1), 9),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
                ('TOPPADDING', (0, 0), (-1, -1), 4),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E0")),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor("#F7FAFC")])
            ]))
            story.append(t)
        else:
            story.append(Paragraph(
                "<i>No metric data available for this period.</i>",
                body_style
            ))

        story.append(Spacer(1, 12))
        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#E2E8F0")))

        # === SECTION 2: INSIGHTS ===
        story.append(Paragraph("2. INSIGHTS — Observations & Longitudinal Context", section_style))
        story.append(Spacer(1, 4))
        narrative = report_data.get("narrative", "Nominal physiological baseline maintained. No significant deviations detected.")
        story.append(Paragraph(narrative, body_style))
        story.append(Spacer(1, 4))

        # Open findings
        findings = report_data.get("open_findings", [])
        if findings:
            story.append(Paragraph("<b>Active Findings:</b>", body_style))
            for finding in findings:
                story.append(Paragraph(
                    f"• <b>{finding.get('severity', 'info').upper()}</b>: {finding.get('description', '')}",
                    body_style
                ))
            story.append(Spacer(1, 4))

        story.append(Spacer(1, 8))
        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#E2E8F0")))

        # === SECTION 3: LIMITATIONS ===
        story.append(Paragraph("3. LIMITATIONS — Data Quality & Coverage Gaps", section_style))
        story.append(Spacer(1, 4))

        limitations = report_data.get("limitations", [])
        if limitations:
            for lim in limitations:
                story.append(Paragraph(f"• {lim}", body_style))
        else:
            story.append(Paragraph(
                "No significant data gaps or quality issues detected during this reporting period.",
                body_style
            ))

        # Baseline status
        baseline_status = report_data.get("baseline_status")
        if baseline_status:
            story.append(Spacer(1, 4))
            story.append(Paragraph(
                f"<b>Baseline Status:</b> {baseline_status}",
                body_style
            ))

        story.append(Spacer(1, 8))
        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#E2E8F0")))

        # === SECTION 4: RECOMMENDED ACTIONS ===
        story.append(Paragraph("4. RECOMMENDED ACTIONS", section_style))
        story.append(Spacer(1, 4))

        actions = report_data.get("recommended_actions", [])
        if actions:
            for action in actions:
                story.append(Paragraph(f"• {action}", body_style))
        else:
            story.append(Paragraph(
                "Continue current health and wellness routines. If you have concerns about any trends, "
                "consult your healthcare provider.",
                body_style
            ))

        story.append(Spacer(1, 12))
        story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#CBD5E0")))

        # === CLOSING REFLECTION ===
        story.append(Spacer(1, 8))
        quote_info = report_data.get("closing_quote", {})
        quote_text = quote_info.get("quote", "Restoration is the completion of effort.")
        author = quote_info.get("author_or_tradition", "Reflective Synthesis")
        story.append(Paragraph(f"\u201c{quote_text}\u201d \u2014 <i>{author}</i>", quote_style))

        # === FOOTER DISCLAIMER (repeated) ===
        story.append(Spacer(1, 16))
        footer_style = ParagraphStyle(
            'FooterDisclaimer',
            parent=styles['Normal'],
            fontSize=7,
            leading=9,
            textColor=colors.HexColor("#A0AEC0"),
            alignment=1  # Center
        )
        story.append(Paragraph(
            "This document was generated by HealthAgent automated analysis. "
            "It does not constitute a medical diagnosis. Consult a physician for health decisions.",
            footer_style
        ))

        doc.build(story)
        return output_path
